import type { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function Layout({ children }: { children: React.ReactNode }) {
    return (
        <main className="bg-slate-300">
            <div className="container m-auto">
                <div className="flex min-h-screen items-center justify-center">
                    <div className="w-full px-8 py-4 md:grid md:grid-cols-2">
                        <div className="hidden bg-black md:block md:overflow-hidden md:rounded-l-3xl">
                            <h1>image</h1>
                        </div>
                        <div className="md:overflow-hidden md:rounded-r-3xl">{children}</div>
                    </div>
                </div>
            </div>
        </main>
    );
}
